[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
  from = "/*"
  to = "https://groovepillows.com/:splat"
  status = 301
  force = true