[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
  from = "/*"
  to = "https://groovepillows.co.uk/:splat"
  status = 301
  force = true


  [[redirects]]
  from = "/"
  to = "https://groovepillows.co.uk"
  status = 301
  force = true